[app]
title = Shop System
package.name = shopsystem
package.domain = org.shop
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf
version = 1.0.0
requirements = python3,kivy,kivymd,sqlalchemy,reportlab,matplotlib,openpyxl,Pillow,plyer,pyzbar
orientation = portrait
fullscreen = 0
android.permissions = INTERNET, CAMERA, READ_EXTERNAL_STORAGE, WRITE_EXTERNAL_STORAGE
android.api = 30
android.minapi = 21
android.ndk = 23b
android.sdk = 30
android.arch = arm64-v8a
android.allow_backup = True
android.add_src =
android.add_assets =
android.add_jar =
android.add_activity =
android.add_meta_data =
android.add_authorities =
android.add_intent_filter =
android.add_java_source =
android.add_java_class =
android.add_kivy_java =
android.add_gradle_dependencies =
android.add_webview_interface =
android.add_signing =
android.add_adb =
android.add_openssl =
android.add_freetype =
android.add_harfbuzz =
android.add_sqlite =
android.add_libpng =
android.add_libjpeg =
android.add_libtiff =
android.add_libwebp =
android.add_libxml2 =
android.add_libxslt =
android.add_libffi =
android.add_libssl =
android.add_libcurl =
android.add_libexpat =
android.add_libz =
android.add_liblzma =
android.add_libiconv =
android.add_libintl =
android.add_libgmp =
android.add_libmpfr =
android.add_libmpc =
android.add_libisl =
android.add_libcloog =
android.add_libppl =
android.add_libglpk =
android.add_libgmpc =
android.add_libmpc =
android.add_libmpfr =
android.add_libgmp =
android.add_libcrypto =
android.add_libssl =
android.add_libcurl =
android.add_libexpat =
android.add_libz =
android.add_liblzma =
android.add_libiconv =
android.add_libintl =
android.add_libgmp =
android.add_libmpfr =
android.add_libmpc =
android.add_libisl =
android.add_libcloog =
android.add_libppl =
android.add_libglpk =
android.add_libgmpc =
android.add_libmpc =
android.add_libmpfr =
android.add_libgmp =
android.add_libcrypto =
android.add_libssl =
android.add_libcurl =
android.add_libexpat =
android.add_libz =
android.add_liblzma =
android.add_libiconv =
android.add_libintl =
android.add_libgmp =
android.add_libmpfr =
android.add_libmpc =
android.add_libisl =
android.add_libcloog =
android.add_libppl =
android.add_libglpk =
android.add_libgmpc =
android.add_libmpc =
android.add_libmpfr =
android.add_libgmp =
android.add_libcrypto =
android.add_libssl =
android.add_libcurl =
android.add_libexpat =
android.add_libz =
android.add_liblzma =
android.add_libiconv =
android.add_libintl =
android.add_libgmp =
android.add_libmpfr =
android.add_libmpc =
android.add_libisl =
android.add_libcloog =
android.add_libppl =
android.add_libglpk =
android.add_libgmpc =
android.add_libmpc =
android.add_libmpfr =
android.add_libgmp =
android.add_libcrypto =
android.add_libssl =
android.add_libcurl =
android.add_libexpat =
android.add_libz =
android.add_liblzma =
android.add_libiconv =
android.add_libintl =
android.add_libgmp =
android.add_libmpfr =
android.add_libmpc =
android.add_libisl =
android.add_libcloog =
android.add_libppl =
android.add_libglpk =
android.add_libgmpc =
android.add_libmpc =
android.add_libmpfr =
android.add_libgmp =
android.add_libcrypto =
android.add_libssl =
android.add_libcurl =
android.add_libexpat =
android.add_libz =
android.add_liblzma =
android.add_libiconv =
android.add_libintl =